apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: background-test-long
spec:
  metrics:
    - name: wait-15
      interval: 1m
      provider:
        job:
          spec:
            backoffLimit: 2
            completions: 1
            template:
              spec:
                containers:
                - name: sleep
                  image: alpine:3.8
                  command: [sh, -c]
                  args: [sleep 1000]
                restartPolicy: Never