apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test-error
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: argoproj/rollouts-demo:red # update it to rollouts-demo:blue to trigger a rollout, as the first time will only create the pods.
          ports:
            - containerPort: 8080