apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: error-test-inline
spec:
  metrics:
    - name: no-image-metric
      count: 1
      failureLimit: 0
      provider:
        job:
          spec:
            backoffLimit: 1
            completions: 1
            activeDeadlineSeconds: 10
            template:
              spec:
                containers:
                  - name: test
                    image: docker.io/library/lol:5 # this image does not exist.
                    command: ["bash"]
                    args: ["-c", "echo 'Hello world! going to exit with 0 (success).' && sleep 10 && exit 0"]
                restartPolicy: Never