apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-test
spec:
  metrics:
    - name: exit-with-0
      provider:
        job:
          spec:
            backoffLimit: 0
            completions: 1
            template:
              spec:
                containers:
                - name: sleep
                  image: alpine:3.8
                  command: [sh, -c]
                  args: [sleep 5 && exit 0]
                restartPolicy: Never