apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  type: ClusterIP
  selector:
    app: trivial-go-web-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
